### PR TITLE
MAPINFO overhaul

### PR DESCRIPTION
**Pull request by DeathEgg**
- Added support for UMAPINFO
- Converted Z/MAPINFO parsing to use OScanner
- Added custom episode support

### CODE REVIEW

**Review by leximayfield — COMMENTED** [review]
Nothing jumps out at me as especially problematic.  However, I do know of at least one bug that this branch introduced that is not in 0.9, and that is a bug on MAP07.  The middle platform to the exit raises twice as far as it's supposed to.  There might be others.  I have created a branch out of this PR so we can get some buildbot action on it.

**Comment by leximayfield** [comment]
image

Getting this when beating E3M8.  The other automatic actions seem okay to me, and I decided to push this branch to our buildbot so we can have more eyes on it.

**Comment by Ch0wW** [comment]
Does your PR have a way to lookup $LANGUAGE_TOKEN strings from `ZMAPINFO`? (check `SIGIL_v1_21.wad` for instance)

Example:

```cpp
map E5M1 "$HUSTR_E5M1"
{
    levelnum = 41
    titlepatch = "WILV40"
    next = "E5M2"
    music = "D_E5M1"
}
```

**Comment by DeathEgg** [comment]
> 
> 
> Does your PR have a way to lookup $LANGUAGE_TOKEN strings from `ZMAPINFO`? (check `SIGIL_v1_21.wad` for instance)
> 
> Example:
> 
> ```c++
> map E5M1 "$HUSTR_E5M1"
> {
>     levelnum = 41
>     titlepatch = "WILV40"
>     next = "E5M2"
>     music = "D_E5M1"
> }
> ```

As far as I know yes. As long as LANGUAGE lumps are stored in engine, then it should be able to look them up.

**Pull request merged**
