### PR TITLE
Add better support for console ports

### PR DESCRIPTION
**Pull request by Ch0wW**
This PR improves support for console porting on Odamex, by doing the following: 

- Add support for the Nintendo Switch port (CMake) ;
- Convert the compilation for the Nintendo Wii (vWii) to CMake ;
- Adds gameplatform_t enum to track easily the changes per platform ;
- Adds joy_deadzone CVAR to control the deadzone of the joysticks ;
- Adds +fastturn CMD & joy_fastsensitivity CVAR to change the sensitivity on the fly ;
- Changed the way responder keys are triggered (see /client/src/cl_responderkeys.cpp), fixes key issues and improve clarity for several consoles
- Wrote README.md documentation files for the Switch/vWii ;
- Joystick support is changed to Game Controller (SDL2.0 only) ; 

**PLEASE NOTE THAT XBOX KEYS in cl_responderkeys.cpp weren't done since I don't have the proper keynames!**

### CODE REVIEW

**Comment by Ch0wW** [comment]
I just converted SDL2's joystick support to Game Controller, in order to make it as a better standard.

**Comment by fuzztooth** [comment]
Will this break xbox?  It's fine since the positives probably outweigh but I want to make sure we know there's a chore to fix it.

**Comment by Ch0wW** [comment]
It currently breaks XBOX inputs for the menu ONLY, as far as I'm aware of. I don't have a way to build on the system, so I cannot test it myself and make sure the buttons work perfectly.

**Comment by Ch0wW** [comment]
I have to make sure the Wii build works fine after fixing a few conflics with the `misc_fixes` branch.

**Review by AlexMax — APPROVED** [review]
LGTM

**Pull request merged**
