### PR TITLE
Add a lost soul limit cvar

### PR DESCRIPTION
**Pull request by electricbrass**
I know there is a desire to limit the number of cvars, but this keeps being an issue with pain elemental bosses in horde mode.

Addresses #707

### CODE REVIEW

**Comment by rakohus** [comment]
I think there still needs to be a reasonable hard cap on souls to prevent a server from spawning thousands of lost souls and killing everything. I'm not sure where that cap should be, but it doesn't seem like a good idea to be limitless.

**Comment by electricbrass** [comment]
Yea, I agree. I actually meant to ask but I forgot. Any idea on a general range? 50? 128? 256?

**Comment by rakohus** [comment]
After doing some research, it looks like boom and higher remove the cap entirely. With that in mind, I would advocate for:

- removing the cap entirely when playing locally (offline)
- capping at something like 128 when playing online

As an aside, the cvar also needs to automatically default to vanilla behavior during vanilla demo playback

**Comment by electricbrass** [comment]
Okay sounds good. I'll do that soon

**Review by leximayfield — APPROVED** [review]
LGTM!

**Pull request merged**
