### PR TITLE
Fix bug 1285: increased max resolution to 8192x6144

### PR DESCRIPTION
**Pull request by bwRavencl**

### CODE REVIEW

**Comment by AlexMax** [comment]
Hi there.  I seem to have some vague recollection that bumping those resolution constants up too far starts causing crashes.  My monitor is 1200p.  Have you been able to test a 4K/8K resolution yourself?

**Comment by bwRavencl** [comment]
> Hi there. I seem to have some vague recollection that bumping those resolution constants up too far starts causing crashes. My monitor is 1200p. Have you been able to test a 4K/8K resolution yourself?

Hi! I only tested on Windows at 4K in 16:9 - so far I experienced no issues.
I couldn't test the 8K so far, maybe if I run it in windowed mode...
I simply assumed it should also work and I simply wanted this change to be somewhat future-proof, to not run into the same issue again in a few years of time...

**Comment by AlexMax** [comment]
> Hi! I only tested on Windows at 4K in 16:9 - so far I experienced no issues.

Okay, cool, let's merge this then.

**Review by AlexMax — APPROVED** [review]
LGTM.

**Pull request merged**
