### PR TITLE
[BUGFIX] Trigger ZDoom action specials on items that are picked up

### LINKED ISSUE #638: [BUG] Hexen Format: Tagged Actions on Pickups Do Not Work
**Describe the bug**
Picking up items with defined actions do not activate on tagged sector targets. Killing a monster DOES activate the tagged action correctly.

**Build that the bug occurred in**
Odamex 10

**To Reproduce**
Run attached wad. Red keycard should lower the floor. Blue keycard should drop the lift. Yellow keycard should open the door.

**Expected behavior**
Activate targets.

**Screenshots, NetDemos, & Crash Dumps**
Test Wad:
[pickupactiontest.zip](https://github.com/odamex/odamex/files/8354006/pickupactiontest.zip)

image

### PR DESCRIPTION
**Pull request by bcahue**
Fixes #638. Previously only action specials would play on killed monsters. Now, items that are consumed by a player will trigger an action special trigger (and then remove said trigger).

### CODE REVIEW

**Comment by rakohus** [comment]
Doesn't work online in coop where the pickup stays on the map

**Comment by rakohus** [comment]
Re-tested on newest commit and it seems fine. Must have been user error on my side.

**Comment by bcahue** [comment]
Here's a vid to confirm: https://www.youtube.com/watch?v=YxGqeJ2daKM

**Review by leximayfield — APPROVED** [review]
LGTM

**Pull request merged**
